{{- if and .Values.prometheus.servicemonitor.enabled
  (and .Values.languagetool.enabled .Values.languagetool.metrics.enabled ) 
}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "collabora-online.fullname" . }}-languagetool
  labels:
    {{- include "collabora-online.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheus.servicemonitor.labels | nindent 4 }}
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      {{- include "collabora-online.selectorLabels" . | nindent 6 }}
      type: languagetool
{{- end }}
